### ISSUE TITLE
temporal_format_property doesn't work with time

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#31]
file:
```
time,event
15:35:00,start
17:35:00,finish
```

pipeline-spec:
```yml
time:
  title: time
  pipeline:

  - run: load
    parameters:
      from: 'time.csv'
      override_fields:
        time:
          type: 'time'
          outputFormat: '%H:%M'
  - run: dump_to_path
    parameters:
      out-path: 'output'
      pretty-descriptor: true
      temporal_format_property: outputFormat
```

stacktrace:
```
ERROR log from processor dump_to_path:
+--------
| ERROR   :Failed to transform row {'event': 'start', 'time': datetime.time(15, 35)}
| Traceback (most recent call last):
|   File "/home/conrad/Projects/whoi/bcodmo_dataflows/dataflows/processors/dumpers/file_formats.py", line 56, in __transform_row
|     for k, v in row.items())
|   File "/home/conrad/Projects/whoi/bcodmo_dataflows/dataflows/processors/dumpers/file_formats.py", line 56, in <genexpr>
|     for k, v in row.items())
|   File "/home/conrad/Projects/whoi/bcodmo_dataflows/dataflows/processors/dumpers/file_formats.py", line 64, in __transform_value
|     return field.descriptor['serializer'](value)
| TypeError: descriptor 'strftime' requires a 'datetime.date' object but received a 'datetime.time'
| ERROR   :Traceback (most recent call last):
| ERROR   :File "/home/conrad/.virtualenvs/pipeline-server/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/dump_to_path.py", line 23, in <module>
| ERROR   :spew_flow(flow(ctx.parameters, ctx.stats), ctx)
| ERROR   :File "/home/conrad/.virtualenvs/pipeline-server/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 181, in __exit__
| ERROR   :spew(self.datapackage, self.resource_iterator, stats=self.stats)
| ERROR   :File "/home/conrad/.virtualenvs/pipeline-server/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 75, in spew
| ERROR   :for rec in res:
| ERROR   :File "/home/conrad/Projects/whoi/bcodmo_dataflows/dataflows/processors/dumpers/dumper_base.py", line 69, in row_counter
| ERROR   :for row in iterator:
| ERROR   :File "/home/conrad/Projects/whoi/bcodmo_dataflows/dataflows/processors/dumpers/file_dumper.py", line 77, in rows_processor
| ERROR   :writer.write_row(row)
| ERROR   :File "/home/conrad/Projects/whoi/bcodmo_dataflows/dataflows/processors/dumpers/file_formats.py", line 70, in write_row
| ERROR   :transformed_row = self.__transform_row(row)
| ERROR   :File "/home/conrad/Projects/whoi/bcodmo_dataflows/dataflows/processors/dumpers/file_formats.py", line 56, in __transform_row
| ERROR   :for k, v in row.items())
| ERROR   :File "/home/conrad/Projects/whoi/bcodmo_dataflows/dataflows/processors/dumpers/file_formats.py", line 56, in <genexpr>
| ERROR   :for k, v in row.items())
| ERROR   :File "/home/conrad/Projects/whoi/bcodmo_dataflows/dataflows/processors/dumpers/file_formats.py", line 64, in __transform_value
| ERROR   :return field.descriptor['serializer'](value)
| ERROR   :TypeError
| ERROR   ::
| ERROR   :descriptor 'strftime' requires a 'datetime.date' object but received a 'datetime.time'
+--------
```

It seems like when it's a `time` type it needs to be handled separately.

I haven't tested with `date`, might also be a problem? Probably not though.

@roll

**Comment by roll** [comment]
Fix - https://github.com/datahq/dataflows/pull/117
