### ISSUE TITLE
Error with extra line and skip_rows parameter

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#33]
If you have a csv with an extra blank line at the end and you want to use `skip_rows` to skip some row earlier on, there is an index error.

pipeline-spec.yaml
```yml
test:
  title: test
  pipeline:
  - run: load
    parameters:
      format: csv
      from: /.../test_blank_line.csv
      headers: 1
      infer_strategy: strings
      cast_strategy: strings
      skip_rows:
      - '#'
```

test_blank_line.csv
```csv
test1,test2
#testing comment
1,2

```

error
```
ERROR log from processor load:
+--------
| Traceback (most recent call last):
|   File "/home/conrad/Projects/whoi/datapackage-pipelines/datapackage_pipelines/specs/../lib/load.py", line 38, in <module>
|     spew_flow(flow(ctx.parameters), ctx)
|   File "/home/conrad/Projects/whoi/datapackage-pipelines/datapackage_pipelines/utilities/flow_utils.py", line 46, in spew_flow
|     datastream = flow.datastream()
|   File "/home/conrad/Projects/whoi/dataflows/dataflows/base/flow.py", line 18, in datastream
|     return self._chain(ds)._process()
|   File "/home/conrad/Projects/whoi/dataflows/dataflows/base/datastream_processor.py", line 72, in _process
|     datastream = self.source._process()
|   File "/home/conrad/Projects/whoi/dataflows/dataflows/base/datastream_processor.py", line 75, in _process
|     self.datapackage = self.process_datapackage(self.datapackage)
|   File "/home/conrad/Projects/whoi/dataflows/dataflows/processors/load.py", line 164, in process_datapackage
|     .format(self.load_source, self.options))
|   File "/home/conrad/Projects/whoi/dataflows/dataflows/processors/load.py", line 161, in process_datapackage
|     return self.safe_process_datapackage(dp)
|   File "/home/conrad/Projects/whoi/dataflows/dataflows/processors/load.py", line 218, in safe_process_datapackage
|     stream.sample, headers=stream.headers,
|   File "/home/conrad/.virtualenvs/pipeline-server/lib/python3.6/site-packages/tabulator/stream.py", line 351, in sample
|     for row_number, headers, row in iterator:
|   File "/home/conrad/.virtualenvs/pipeline-server/lib/python3.6/site-packages/tabulator/stream.py", line 596, in force_strings_processor
|     for row_number, headers, row in extended_rows:
|   File "/home/conrad/.virtualenvs/pipeline-server/lib/python3.6/site-packages/tabulator/stream.py", line 559, in builtin_processor
|     if self.__check_if_row_for_skipping(row_number, headers, row):
|   File "/home/conrad/.virtualenvs/pipeline-server/lib/python3.6/site-packages/tabulator/stream.py", line 628, in __check_if_row_for_skipping
|     if any(map(match, self.__skip_rows_by_comments)):
|   File "/home/conrad/.virtualenvs/pipeline-server/lib/python3.6/site-packages/tabulator/stream.py", line 625, in <lambda>
|     row[0].startswith(comment)) if len(comment) > 0
| IndexError: list index out of range
```

We already add a custom parameter to the load step that deletes empty rows. However, it doesn't make it to that processor because it runs after the load step.

@roll

**Comment by roll** [comment]
Fixed in `tabulator@1.31`
